### ISSUE TITLE
Not all 10.2 emojis are showing up on the keyboard

### ISSUE THREAD

**Issue by Zeebins** [PoomSmart/EmojiPort-WT#1]
I noticed that when I was looking through the emojis after installing some of that flags are missing on the keyboard (still show up in the predictive text though). On a device running 10.2 there are 5 additional flag emojis before the first flag On 10.1.1 + Emoji10. And yes, I do have the appropriate font downloaded. (More may be missing but those are the ones I noticed)

**Comment by PoomSmart** [comment]
Resolved.
