### ISSUE TITLE
New emojis are not being added to recently used emojis list

### ISSUE THREAD

**Issue by ghost** [PoomSmart/EmojiPort-WT#13]

**Comment by 2600box** [comment]
You don't specify any details about your setup.

For reference, I have the latest version of emojiport on iOS 10.1.1 and new emoji are added to frequently used.

**Comment by ghost** [comment]
You are right. I am using 11.3.1 with the latest version but it has always been like that on any device and any iOS I used.

**Comment by ghost** [comment]
that is weird indeed, I'm not having this issue while being on ios 10.3.3 using emojiport version 1.2.2F.

**Comment by ghost** [comment]
So this 🥶 emoji appears in recently used emojis sections for you?

**Comment by ghost** [comment]
![testrecentemojis](https://user-images.githubusercontent.com/17068496/48002108-ddafab00-e10a-11e8-9a8f-b63f8e18b26f.PNG)

the new ones do indeed work for me. "see screenshot"

**Comment by ghost** [comment]
So it is an iOS 11 bug then.

**Comment by ghost** [comment]
The latest version of EmojiPort does not have this problem.
