### ISSUE TITLE
EmojiPort does not remember the last scroll position

### ISSUE THREAD

**Issue by ghost** [PoomSmart/EmojiPort-WT#16]
[Here is a video.](https://www.youtube.com/watch?v=8xsdGuZj8VQ&feature=youtu.be)

**Comment by PoomSmart** [comment]
This is more like the stock behavior and none of EmojiPort's concerns; iOS will somehow round the scroll position possibly via `-[UIKeyboardEmojiCollectionInputView indexForPrettyCategoryDisplay:]`.

**Comment by ghost** [comment]
You are right. Can you fix that iOS issue please?

**Comment by PoomSmart** [comment]
https://www.dropbox.com/s/sm4eautfpevc404/com.ps.emojum_0.0.1_iphoneos-arm.deb

**Comment by ghost** [comment]
[Thank you but that tweak doesn't seem to be working.](https://youtu.be/2rYMgQ4Kd5E)

**Comment by PoomSmart** [comment]
See if before you dismiss the keyboard, you tap on some emoji then the scroll index would occasionally persist.

**Comment by ghost** [comment]
[Still doesn't work.](https://youtu.be/_sgA7UvXufQ)
