### ISSUE TITLE
Emoji font won‘t apply

### ISSUE THREAD

**Issue by Ectalite** [PoomSmart/EmojiPort-WT#17]
Hey,
I have an iphone 8 and installed EmojiPort (ios 10.0 - 11.4.1) such as I‘m on ios 11.4.1. The new font doesn‘t appear to work because I have the same emojis as before and doesn‘t have the new ones of ios 12. 
I tested other solutions, but it doesn‘t want to work.

**Comment by Ectalite** [comment]
I found that solution, could you add it in your guide ? It‘s not very clear.
https://www.reddit.com/r/jailbreak/comments/9u7pwo/discussion_ios_121_emoji_not_showing_with/?st=JSFSBKSX&sh=0d88fa2f

**Comment by Ectalite** [comment]
And after testing emojifont manager won‘t work properly, but replacing it system fonts works

**Comment by PoomSmart** [comment]
Provide more details such as the version of EmojiPort and EmojiFontManager installed, from which repo the tweaks are downloaded from, how it does not work, and/or the apps that Emoji cannot work on.

As for updating the guide, no. There is nothing wrong with the guide. One has to read carefully.

**Comment by Ectalite** [comment]
Like I said previously I installed the latest version of EmojiPort (IOS 10.0 - 11.4) version 1.2.4 and the latest version of EmojiFontManager (0.0.5f) and i‘m on an iPhone8 (10,4) on ios 11.4.1
I wanted to use the seconde option of your guide so I installed the latest version of Emoji Ios (12.1) and I selected it EmojiFontManager.
After respringing nothing changed in the emoji keyboard and I hadn‘t the new emojis.
I saw after that on reddit a guide to "fix" this problem (it‘s the previews link) and it worked.
So i think that there is a problem for ios 11.4.1 and I created this issue on github.

**Comment by PoomSmart** [comment]
Alright.

If I understood correctly, your solution is to follow the OP from your given link. That and the guide on my repo are indifferent so there must be something weird going on.

**Comment by Ectalite** [comment]
Yup, 
You can make what you want, but I just saw that the option 2 of your guide (and so EmojiFontManager) could be broken for ios 11.4.1 or for my device.

**Comment by PoomSmart** [comment]
You seem to be the only one reporting this issue on iOS 11.4.1, also I have tested EFM on iOS 12.1.1 with no bugs whatsoever. I might reopen this issue if more people confirmed so.

**Comment by sekhonanmol** [comment]
I’m having the same issue on iPhone X (11.4.1) Jailbroken. Installed everything as instructed, no new emojis are showing up. Help Please!

**Comment by Tee-Dot** [comment]
Won't work for me either, despite following the guide step for step. I'm on an iPhone 8 Plus (11.4.1) and have tried everything but nothing seems to work. The emojis are not showing up on my keyboard, nor in any apps. I've tried both placing the file manually in the correct directory and also using EFM, no success with both. Other people that have reported issues elsewhere also were on 11.4.1, so that seems to be the issue.

iPhone 8 Plus, iOS 11.4.1, Jailbroken with unc0ver 5.2.0
EmojiPort (iOS 10.0-11.4) Version 1.3.0
EmojiFontManager Version 0.0.7.1
Everything from the PoomSmart Repo.

Any help would be greatly appreciated!

**Comment by sekhonanmol** [comment]
Why isn’t he replying? We need a solution for this.
