### ISSUE TITLE
Emojis working intermittently 

### ISSUE THREAD

**Issue by xaviervalarino** [PoomSmart/EmojiPort-WT#19]
After installing EmojiPort with Emoji iOS 13.2, EmojiAttributes, EmojiFontManager and EmojiLibrary, I've been encountering a strange issue where emojis will stop working system wide. Usually exiting and reopening the app I am trying to use an emoji in will fix the issue. I'm having a hard time finding a pattern as to why this is happening. Maybe it happens more often in low power mode?

On iPhone 6 12.4.4 with Checkra1n 9.6.0
<img width="375" alt="emoji-issuepng" src="https://user-images.githubusercontent.com/4262486/72376349-a6e80400-36c2-11ea-81db-59903abd07e9.png">

**Comment by PoomSmart** [comment]
Possibly sandbox issue - thus jailbreak-related. No further ideas yet.
