### ISSUE TITLE
Keyboard crash randomly

### ISSUE THREAD

**Issue by ridalarry** [PoomSmart/EmojiPort-WT#2]
This is CrashReporter log
http://pastebin.com/WaNnQrRz

**Comment by ridalarry** [comment]
I have tried to know the cause of this and I noticed that its caused by a few keyboard symbols whenever you type it specially if it was the first in the line or following space and these are the bugged symbols 
[]{}%^*+=\|_~<>€£¥•-/$

**Comment by ridalarry** [comment]
I have found a temp solution for whomever facing the same issue, remove your language keyboard and use SwiftKey keyboard and add all the keyboard languages that you need. You can keep Emoji and any custom keyboards, just remove the default ones except for emoji.

**Comment by ridalarry** [comment]
@PoomSmart After more checks I have noticed that this issue only happens to the main keyboard which is English, IDK if it happens to other languages too, but it doesn't occur when using the Arabic keyboard. I have found another temp solution for it, which is when the keyboard crash the option to switch keyboard is still functional, switch to another keyboard then back to English, and it will be fixed temporary.

**Comment by PoomSmart** [comment]
The crash issue has gone.
