### ISSUE TITLE
[ v1.3.6 ] iOS 10.3.3 Springboard Crashes (log)

### ISSUE THREAD

**Issue by foxnoodles** [PoomSmart/EmojiPort-WT#21]
No efm installed just EmojiPort and its dependencies.

EmojiPort Resources - 1.3.0-b1
EmojiAttributes - 1.5.0-b4
EmojiLibrary - 1.4.0-b1

Heres the log:
[crashlog.txt](https://github.com/PoomSmart/EmojiPort-WT/files/7993964/crashlog.txt)

Downgrading to 1.3.5 fixes it but iOS 15 emoji font does not work (if u install EFM and select it of course)

**Comment by PoomSmart** [comment]
Hopefully fixed in EmojiAttributes b5

**Comment by foxnoodles** [comment]
Installed all updates. Crash was fixed and everything seems to be working now.

Also, this might be unrelated but on iOS 9.3.x emojis appear in keyboard but don't show up when you type (they appear as question marks)
