### ISSUE TITLE
Issue with emojis showing on some apps but not other apps

### ISSUE THREAD

**Issue by hoborobossj** [PoomSmart/EmojiPort-WT#3]
Hello I had installed iOS 10.2 emojis on my iPhone 6s Plus running iOS 10.1.1. I had no problems with it until one day I installed a custom font. I tried reinstalling the emojis by redoing the steps with iFile and reinstalling emojiattributes and emoji10. After doing this my 10.2 emojis only show on my keyboard on some apps and when pasting or typing a 10.2 emoji on the apps that don't show the emojis on the keyboard I get question mark boxes.

**Comment by hoborobossj** [comment]
I have removed my custom font if that helps but the emojis still don't show on those apps

**Comment by PoomSmart** [comment]
Which custom font you are talking about?

**Comment by hoborobossj** [comment]
"Komika Display" in BytaFont tweak mode

**Comment by hoborobossj** [comment]
I found out that the font wasn't the problem but phantom for Snapchat blocking the tweaks but I still can't see the new emojis on my keyboard

**Comment by PoomSmart** [comment]
Phantom has to be updated to include Emoji10 for iOS 10 tweak.

**Comment by hoborobossj** [comment]
I am sorry sir but my Snapchat still doesn't have the emojis even after updating phantom lite and enabling emojiattributes

**Comment by PoomSmart** [comment]
That is because Phantom hasn't included Emoji10WT.dylib as whitelist. What you may want to try: go to /Library/MobileSubstrate/DynamicLibraries and rename Emoji10WT.dylib to Emoji10PS.dylib / Emoji10WT.plist to Emoji10PS.plist

**Comment by hoborobossj** [comment]
Gracias
