### ISSUE TITLE
Some problems with emoji keyboard on iOS 10.2

### ISSUE THREAD

**Issue by tavrez** [PoomSmart/EmojiPort-WT#4]
Hello, Thanks for your EmojiPort app, I've found some problems and I like to share them with you:

1. Female gymnasts is missing: I've tested this in iOS 10.2 with 11.1 font, everything is fine except this one. I should also note that this emoji is fine in non-jailbroken state and 11.1 fonts installed, it only go away when we jailbreak and have this tweak installed(a "..." will appear instead of it)

2. When we clear some new emojis with backspace, they won't cleared with one backspace, they change state, from female to male, from color skinned into yellow, from small to big(in messages screen), then become cleared.

Sorry I wasn't sure about if this problems are related to this tweak or EmojiLibrary, Thanks again!

**Comment by PoomSmart** [comment]
Resolved bugs from combination of EmojiAttributes, EmojiPort (iOS 10) and EmojiLibrary, except for the three new flags.
