### ISSUE TITLE
Meridian EmojiPort incompatibility

### ISSUE THREAD

**Issue by CzXe7** [PoomSmart/EmojiPort-WT#6]
EmojiPort doesn't work on Meridian. Neither does it work in a manual mode. I've tried everything. Messages crashes instantly. Here's my crashlog for it: 
https://pastebin.com/AVKSNqup

Cheers, 
-CZ

**Comment by ghost** [comment]
experiencing the same issue but on ios 10.3.3 using h3lix jailbreak. stable version for me is 1.2.2F anything above that causes crashes when attempting to open the emoticon tab.

**Comment by jakesamuals** [comment]
On Yalu 10.1.1 iPhone SE, EmojiPort higher than vers. 1.2.2 and Messages crashes instantly upon opening. No problem however in Whatsapp or within Chrome or Safari.
