### ISSUE TITLE
Some emojis not displayed correctly 

### ISSUE THREAD

**Issue by iM4CH3T3** [PoomSmart/EmojiPort-WT#7]
These red circled emojis aren’t displayed correctly on iPhone 7 iOS 1131 
These 👇👇👇
![Image](https://i.imgur.com/bftynfo.jpg)
Got displayed as these 👇👇👇
![Image](https://i.imgur.com/Rj3lBCU.jpg)
![Image](https://i.imgur.com/vipt26V.jpg)
![Image](https://i.imgur.com/cXdS0Z1.jpg)
![Image](https://i.imgur.com/EEDXRv1.jpg)
![Image](https://i.imgur.com/K6GZHIb.jpg)
![Image](https://i.imgur.com/JUiIuU6.jpg)

**Comment by iM4CH3T3** [comment]
Noticed it’s actually 4 couples that argent displayed right...
![Image](https://i.imgur.com/5cTl2Du.jpg)

**Comment by mkizzle2906** [comment]
Same issue
