### ISSUE TITLE
Blank emoji on iOS 10.2

### ISSUE THREAD

**Issue by antonioag95** [PoomSmart/EmojiPort-WT#8]
I'm on iOS 10.2 and trying to add new iOS 12.1 emoji on my iPhone I'm facing a problem, all emoji are just blank. 

What did I do:

Went to /System/Library/Fonts/Core renamed both "AppleColorEmoji@2x.ttc" and "AppleColorEmoji@2x.ccf" adding the extension ".bak" for backup purpose. I downloaded the file number 1 from your manual guide, corresponding to the font for iOS 10+. I pasted it in the same folder as before and at the end I installed the right version of EmojiPort from your repo. 
While investigating the issue I noticed that my original .ttc file is only a few kilobytes and my original .ccf is about 42MB (I can't exactly remember), while the .ttc downloaded from you weights about as much as my original .ccf file. 
I currently restored my backup files and everything is working as before.

**Comment by mkizzle2906** [comment]
Same issue on my 10.1.1 & 9.3.3 devices
