### ISSUE TITLE
EmojiAttributes & EmojiLibrary new update cause safemode on iOS 8.4 and some emoji only have one skintone

### ISSUE THREAD

**Issue by mkizzle2906** [PoomSmart/EmojiPort-WT#9]
I update both of them on my 6Plus 8.4 and replace a new font file then they put my device into safemode. I tried to replace old font file & downgrade but still stuck in safemode. Only EmojiAttributes 1.3.13 & EmojiLibrary 1.0.12 work. Before updating to the lastest everything work fine. Can you check it ??? And after updating EmojiDarkStyle causes this on my iOS 8.4 devices
![img_3965](https://user-images.githubusercontent.com/32402155/46807418-0eaef100-cd94-11e8-8b1d-5c985c646abe.PNG)

Another problem is this emoji dont have skin selection. The lastest update of EmojiPort 10 - 11.4 fixed the people skin tone problems, 
but this emoji still only have 1 skin. (both iOS 9, 10 & 11)
![img_1407](https://user-images.githubusercontent.com/32402155/46806451-d0183700-cd91-11e8-9632-2f835359855f.PNG)

This emoji only on iOS 10 has one skin too
![img_3421](https://user-images.githubusercontent.com/32402155/46806704-749a7900-cd92-11e8-840c-959dd25f7552.PNG)

**Comment by maximoney1994** [comment]
I can confirm the latest emoji attributes and library update work on ios 10.3.3 the emoji port update however doesn't and fails to install.
I can also confirm the shaking hands emoji indeed only has 1 skin even with the latest emoji attributes and library installed on ios 10.3.3.

**Comment by mkizzle2906** [comment]
yeah they work fine on both iOS 9, 10 & 11 on my devices with new EmojiAttributes 1.3.14f (only shaking emoji still has only 1 skin)
The problem is EmojiLibrary sends my 6+ 8.4 to safemode & EmojiDarkStyle shows text instead of icon
